CREATE TABLE `sector_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sector_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '板块代码，如BK0420',
  `sector_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '板块名称',
  `latest_price` int DEFAULT NULL COMMENT '最新价',
  `change_percent` int DEFAULT NULL COMMENT '涨跌幅',
  `total_market_cap` bigint DEFAULT NULL COMMENT '板块总市值',
  `change_value` int DEFAULT NULL COMMENT '涨跌额',
  `turnover_rate` int DEFAULT NULL COMMENT '换手率',
  `leader_stock_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '龙头股票代码',
  `leader_stock_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '龙头股票名称',
  `leader_stock_change_percent` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '龙头股票涨跌幅',
  `up_numbe` int DEFAULT NULL COMMENT '上涨家数',
  `down_numbe` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '下跌家属',
  `trade_date` date DEFAULT NULL COMMENT '交易日',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `uk_sector_code` (`sector_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=218 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='板块信息表';
CREATE TABLE `stock_capital_flow` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
  `type` char(1) DEFAULT NULL COMMENT '1沪，0深',
  `stock_code` varchar(10) NOT NULL COMMENT '股票代码',
  `stock_name` varchar(50) NOT NULL COMMENT '股票名称',
  `related_code` varchar(100) DEFAULT NULL COMMENT '相关板块code',
  `related_name` varchar(100) DEFAULT NULL COMMENT '相关板块名称',
  `latest_price` decimal(10,2) DEFAULT NULL COMMENT '最新价（元）',
  `change_percent` decimal(6,2) DEFAULT NULL COMMENT '涨跌幅（%）',
  `main_net_inflow` decimal(15,2) DEFAULT NULL COMMENT '主力净流入净额（元）',
  `main_net_inflow_ratio` decimal(6,2) DEFAULT NULL COMMENT '主力净流入净占比（%）',
  `super_large_net_inflow` decimal(15,2) DEFAULT NULL COMMENT '超大单净流入净额（元）',
  `super_large_net_inflow_ratio` decimal(6,2) DEFAULT NULL COMMENT '超大单净流入净占比（%）',
  `large_net_inflow` decimal(15,2) DEFAULT NULL COMMENT '大单净流入净额（元）',
  `large_net_inflow_ratio` decimal(6,2) DEFAULT NULL COMMENT '大单净流入净占比（%）',
  `medium_net_inflow` decimal(15,2) DEFAULT NULL COMMENT '中单净流入净额（元）',
  `medium_net_inflow_ratio` decimal(6,2) DEFAULT NULL COMMENT '中单净流入净占比（%）',
  `small_net_inflow` decimal(15,2) DEFAULT NULL COMMENT '小单净流入净额（元）',
  `small_net_inflow_ratio` decimal(6,2) DEFAULT NULL COMMENT '小单净流入净占比（%）',
  `change_percent_5d` decimal(6,2) DEFAULT NULL COMMENT '5日涨跌幅（%）',
  `main_net_inflow_5d` decimal(15,2) DEFAULT NULL COMMENT '5日主力净流入净额（元）',
  `main_net_inflow_ratio_5d` decimal(6,2) DEFAULT NULL COMMENT '5日主力净流入净占比（%）',
  `super_large_net_inflow_5d` decimal(15,2) DEFAULT NULL COMMENT '5日超大单净流入净额（元）',
  `super_large_net_inflow_ratio_5d` decimal(6,2) DEFAULT NULL COMMENT '5日超大单净流入净占比（%）',
  `large_net_inflow_5d` decimal(15,2) DEFAULT NULL COMMENT '5日大单净流入净额（元）',
  `large_net_inflow_ratio_5d` decimal(6,2) DEFAULT NULL COMMENT '5日大单净流入净占比（%）',
  `medium_net_inflow_5d` decimal(15,2) DEFAULT NULL COMMENT '5日中单净流入净额（元）',
  `medium_net_inflow_ratio_5d` decimal(6,2) DEFAULT NULL COMMENT '5日中单净流入净占比（%）',
  `small_net_inflow_5d` decimal(15,2) DEFAULT NULL COMMENT '5日小单净流入净额（元）',
  `small_net_inflow_ratio_5d` decimal(6,2) DEFAULT NULL COMMENT '5日小单净流入净占比（%）',
  `change_percent_10d` decimal(6,2) DEFAULT NULL COMMENT '10日涨跌幅（%）',
  `main_net_inflow_10d` decimal(15,2) DEFAULT NULL COMMENT '10日主力净流入净额（元）',
  `main_net_inflow_ratio_10d` decimal(6,2) DEFAULT NULL COMMENT '10日主力净流入净占比（%）',
  `super_large_net_inflow_10d` decimal(15,2) DEFAULT NULL COMMENT '10日超大单净流入净额（元）',
  `super_large_net_inflow_ratio_10d` decimal(6,2) DEFAULT NULL COMMENT '10日超大单净流入净占比（%）',
  `large_net_inflow_10d` decimal(15,2) DEFAULT NULL COMMENT '10日大单净流入净额（元）',
  `large_net_inflow_ratio_10d` decimal(6,2) DEFAULT NULL COMMENT '10日大单净流入净占比（%）',
  `medium_net_inflow_10d` decimal(15,2) DEFAULT NULL COMMENT '10日中单净流入净额（元）',
  `medium_net_inflow_ratio_10d` decimal(6,2) DEFAULT NULL COMMENT '10日中单净流入净占比（%）',
  `small_net_inflow_10d` decimal(15,2) DEFAULT NULL COMMENT '10日小单净流入净额（元）',
  `small_net_inflow_ratio_10d` decimal(6,2) DEFAULT NULL COMMENT '10日小单净流入净占比（%）',
  `trade_date` date NOT NULL COMMENT '交易日',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_trade_date` (`trade_date`),
  KEY `idx_stock_code` (`stock_code`),
  KEY `idx_stock_name` (`stock_name`)
) ENGINE=InnoDB AUTO_INCREMENT=14635 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='股票资金流向日报表';